# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='words',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
